### ISSUE TITLE
SyntaxError: Parse error tests.webpack.js:5941

### ISSUE THREAD

**Issue by Volodymyr128** [justinwoo/react-karma-webpack-testing#3]
On `npm test` got:

```
PhantomJS 1.9.8 (Windows 7 0.0.0) ERROR
  SyntaxError: Parse error
  at D:/Projects/betbull_web/tests.webpack.js:5941
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 0 of 0 ERROR (0.083 secs / 0 secs)
```

**Comment by mrozbarry** [comment]
Same issue here using karma-webpack and coffee-script unit tests.  I can post my config file if that helps.

**Comment by mbektimirov** [comment]
Has someone figured out the problem? Having the same error, seems like some files are not preprocessing with webpack.

**Comment by mmahalwy** [comment]
having the same problem. Any luck anyone?

**Comment by justinwoo** [comment]
Are all of you using PhantomJS 1.9.8? I think everyone else is using PhantomJS 2.x

**Comment by DoniaMroua** [comment]
On npm test got:
PhantomJS 1.9.8 (Windows 8 0.0.0) ERROR
  SyntaxError: Parse error
  at c:/Users/Maher/documents/Aptana Studio 3 Workspace/CookingRecipe/spec/javascripts/sample.coffee:1

Same issue Using coffee-Script. Any help please ?

**Comment by justinwoo** [comment]
Sorry, I don't use this anymore.
