### ISSUE TITLE
The Amazing debug.html

### ISSUE THREAD

**Issue by youngBrain1893** [justinwoo/react-karma-webpack-testing#9]
When I was reading your [post](http://qiita.com/kimagure/items/f2d8d53504e922fe3c5c) I found the `debug.html` is amazing but you didn't mentioned how did you implement that in your post, If I what to implement that, what should I do? 

THX

**Comment by justinwoo** [comment]
It should work if you click "debug" in the karma test page that comes up in the browser

**Comment by youngBrain1893** [comment]
it did work out, thanks a lot.
